security:
    password_hashers:
        App\Entity\Client:
            algorithm: auto
        App\Entity\Employe:
            algorithm: auto

    providers:
        chain_provider:
            chain:
                providers: ['client_provider', 'employe_provider']

        client_provider:
            entity:
                class: App\Entity\Client
                property: AdresseEmail

        employe_provider:
            entity:
                class: App\Entity\Employe
                property: AdresseEmail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/connexion
            stateless: true
            json_login:
                check_path: /api/connexion
                username_path: AdresseEmail
                password_path: MotDePasse
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                provider: chain_provider

        api:
            pattern: ^/api
            stateless: true
            jwt:
                provider: chain_provider  # Spécifie le fournisseur pour le firewall JWT

    access_control:
        - { path: ^/api/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/entrepots, roles: ROLE_APPROVISIONNEMENT  }
        - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/appro, roles: ROLE_APPROVISIONNEMENT }
        - { path: ^/api/inscription/employe, roles: ROLE_SUPER_ADMIN }
