security:
    password_hashers:
        App\Entity\Client:
            algorithm: auto
        App\Entity\Employe:
            algorithm: auto

    providers:
        chain_provider:
            chain:
                providers: ['client_provider', 'employe_provider']

        client_provider:
            entity:
                class: App\Entity\Client
                property: AdresseEmail

        employe_provider:
            entity:
                class: App\Entity\Employe
                property: AdresseEmail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/connexion
            stateless: true
            json_login:
                check_path: /api/connexion
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                provider: chain_provider

        api:
            pattern: ^/api
            stateless: true
            provider: chain_provider
            jwt: ~

        main:
            pattern: ^/
            stateless: false
            provider: chain_provider
            form_login:
                login_path: app_connexion_web
                check_path: app_connexion
                default_target_path: app_connexion_web
            logout:
                path: /logout
                target: /connexion

    access_control:
        - { path: ^/api/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/entrepots, roles: ROLE_SUPER_ADMIN }
        - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/appro, roles: ROLE_APPROVISIONNEMENT }
        - { path: ^/appro, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/super-admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/commercial, roles: ROLE_COMMERCIAL }
        - { path: ^/commercial, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }