security:
    password_hashers:
        App\Entity\Client:
            algorithm: auto
        App\Entity\Employe:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Client  # or App\Entity\User if you have a common base class
                property: AdresseEmail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/connexion
            stateless: true
            json_login:
                check_path: /api/connexion
                username_path: AdresseEmail
                password_path: MotDePasse
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/entrepots, roles: ROLE_PARTICULIER }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
