controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


connexion:
    path: /connexion
    controller: App\Controller\api\ConnexionController::connexion
    methods: POST


  
api_inscription:
  path: /api/inscription
  controller: 'App\Controller\api\InscriptionController::inscription'
  methods: ['POST']
api_inscription_employe:
  path: /api/inscription/employe
  controller: 'App\Controller\api\InscriptionEmployeController::inscription'
  methods: ['POST']

api_inscription_employe_employes:
  path: /api/inscription/employe/employes
  controller: 'App\Controller\api\InscriptionEmployeController::tousLesEmployes'
  methods: ['GET']

api_inscription_employe_services:
  path: /api/inscription/employe/services/{service}
  controller: 'App\Controller\api\InscriptionEmployeController::employesParService'
  methods: ['GET']

api_modifier_employe:
  path: /api/inscription/employe/employe/{id}
  controller: 'App\Controller\api\InscriptionEmployeController::modifierEmploye'
  methods: ['PUT']

panier_ajouter:
    path: /panier/ajouter
    controller: 'App\Controller\PanierController::ajouterProduitAuPanier'
    methods: ['POST']

panier_afficher:
    path: /panier
    controller: 'App\Controller\PanierController::afficherPanier'
    methods: ['GET']

panier_modifier:
    path: /panier/modifier/{id}
    controller: 'App\Controller\PanierController::modifierDetailPanier'
    methods: ['PUT']

panier_supprimer:
    path: /panier/supprimer/{id}
    controller: 'App\Controller\PanierController::supprimerDetailPanier'
    methods: ['DELETE']

panier_vider:
    path: /panier/vider
    controller: 'App\Controller\PanierController::viderPanier'
    methods: ['DELETE']


# config/routes.yaml

calculate_distance:
    path: /distance/{postalCode1}/{masseKg}
    controller: 'App\Controller\DistanceController::calculateDistance'
    methods: GET
    requirements:
        postalCode1: '\d+'
        masseKg: '[\d,]+(\.\d+)?'

api_entrepots_index:
  path: /api/entrepots
  controller: 'App\Controller\api\EntrepotController::index'
  methods: [GET]

api_entrepots_show_all:
  path: /api/entrepots/all
  controller: 'App\Controller\api\EntrepotController::showAll'
  methods: [GET]

api_entrepots_create:
  path: /api/entrepots/create
  controller: 'App\Controller\api\EntrepotController::create'
  methods: [POST]

api_entrepots_show:
  path: /api/entrepots/{id}
  controller: 'App\Controller\api\EntrepotController::show'
  methods: [GET]

api_entrepots_update:
  path: /api/entrepots/{id}
  controller: 'App\Controller\api\EntrepotController::update'
  methods: [PUT]

api_entrepots_delete:
  path: /api/entrepots/{id}
  controller: 'App\Controller\api\EntrepotController::delete'
  methods: [DELETE]
app_entrepot_codes_postaux:
  path: /api/entrepots/codes-postaux
  controller: 'App\Controller\api\EntrepotController::codesPostaux'
  methods: ['GET']
# config/routes.yaml

prix_matiere_premiere:
  path: /prix-matiere-premiere
  controller: 'App\Controller\MatierePremiereController::getPrixMatierePremiere'
  methods: ['GET']
# config/routes.yaml
holidays:
    path: /holidays/{year}
    controller: App\Controller\HolidayController::index
checkout:
  path: /checkout
  controller: App\Controller\PaymentController::checkout
  methods: ['GET']

create_checkout_session:
  path: /create-checkout-session
  controller: App\Controller\PaymentController::createCheckoutSession
  methods: ['POST']

payment_success:
  path: /payment/success
  controller: App\Controller\PaymentController::paymentSuccess
  methods: ['GET']

payment_cancel:
  path: /payment/cancel
  controller: App\Controller\PaymentController::paymentCancel
  methods: ['GET']
api_produits_search_nom:
  path: '/api/produits/search/nom/{nom_produit}'
  controller: 'App\Controller\ConfigurateurController::searchByNom'
  methods: 'GET'

api_produits_search_nom_masse:
  path: '/api/produits/search/nom/{nom_produit}/masse/{masse_produit}'
  controller: 'App\Controller\ConfigurateurController::searchByNomAndMasse'
  methods: 'GET'
  requirements:
    masse_produit: '.+'  # Accepte n'importe quelle chaîne de caractères

app_inscriptionParticulier:
    path: '/inscriptionParticulier'
    controller: 'App\Controller\api\InscriptionController::index'
    methods: ['GET']

inscription_pro:
    path: /inscription/pro
    controller: App\Controller\api\InscriptionController::pro
  
# config/routes.yaml
app_index:
    path: /accueil
    controller: 'App\Controller\IndexController::index'

app_choix:
    path: /choix
    controller: 'App\Controller\IndexController::choix'

app_connexion_web:
    path: /connexion
    controller: App\Controller\IndexController::connexion
    methods: ['GET']
# config/routes.yaml

app_super_admin:
    path: /super-admin
    controller: App\Controller\IndexController::superAdmin
    methods: GET
# config/routes.yaml

email_send:
    path: /send-email
    controller: 'App\Controller\EmailController::sendEmail'
    methods: ['GET', 'POST']
app_appro:
    path: /appro
    controller: App\Controller\IndexController::appro
    methods: GET
api_fournisseur_index:
  path: '/api/fournisseurs/'
  controller: 'App\Controller\api\FournisseurApiController::index'
  methods: ['GET']

api_fournisseur_new:
  path: '/api/fournisseurs/nouveau'
  controller: 'App\Controller\api\FournisseurApiController::nouveau'
  methods: ['POST']

api_fournisseur_afficher:
  path: '/api/fournisseurs/{id}'
  controller: 'App\Controller\api\FournisseurApiController::afficher'
  methods: ['GET']
  requirements:
    id: \d+   # contrainte pour id : uniquement des chiffres

api_fournisseur_modifier:
  path: '/api/fournisseurs/{id}/modifier'
  controller: 'App\Controller\api\FournisseurApiController::modifier'
  methods: ['PUT', 'PATCH']
  requirements:
    id: \d+   # contrainte pour id : uniquement des chiffres

api_fournisseur_supprimer:
  path: '/api/fournisseurs/{id}'
  controller: 'App\Controller\api\FournisseurApiController::supprimer'
  methods: ['DELETE']
  requirements:
    id: \d+   # contrainte pour id : uniquement des chiffres

api_fournisseur_recherche:
  path: '/api/fournisseurs/recherche'
  controller: 'App\Controller\api\FournisseurApiController::recherche'
  methods: ['GET']

# config/routes.yaml

api_produit_add:
    path: /api/produits
    controller: App\Controller\api\ProduitController::addProduit
    methods: POST

api_produits_get:
    path: /api/produits
    controller: App\Controller\api\ProduitController::getProduits
    methods: GET
app_produits:
    path: /produit
    controller: App\Controller\IndexController::produits
    methods: GET
# config/routes/api.yaml
api_produit_fournisseur_add:
    path: /api/produit-fournisseur
    controller: 'App\Controller\api\ProduitFournisseurController::addProduitFournisseur'
    methods: ['POST']

api_produit_fournisseur_update:
    path: /api/produit-fournisseur/{id}
    controller: 'App\Controller\api\ProduitFournisseurController::updateProduitFournisseur'
    methods: ['PUT']
    requirements:
        id: '\d+'

api_produit_fournisseur_get:
    path: /api/produit-fournisseur/{id}
    controller: 'App\Controller\api\ProduitFournisseurController::getProduitFournisseur'
    methods: ['GET']
    requirements:
        id: '\d+'

api_produit_fournisseur_get_all:
    path: /api/produit-fournisseur
    controller: 'App\Controller\api\ProduitFournisseurController::getAllProduitFournisseur'
    methods: ['GET']

api_produit_fournisseur_livraison_arrivee_stock:
    path: '/api/produit-fournisseur/{id}/livraison-arrivee/stock'
    controller: 'App\Controller\api\ProduitFournisseurController::livraisonArriveeStock'
    methods: ['PUT']
# config/routes.yaml

check_role:
    path: /api/check-role
    controller: App\Controller\api\CheckRoleController::checkRole
    methods: ['GET']
# config/routes.yaml

app_logout:
    path: /logout
    controller: App\Controller\LogoutController::logout
    methods: [GET]


app_produit_bis:
    path: /produit-bis
    controller: App\Controller\IndexController::produitBis
    methods: GET
# config/routes.yaml

panier_calculer:
    path: /panier/calculer
    controller: App\Controller\PanierCalculController::calculerPanier
    methods: [POST]

# config/routes.yaml

api_update_stock:
    path: /api/mise-a-jour-stock
    controller: App\Controller\api\StockController::updateStock
    methods: [POST]
# config/routes.yaml
api_commandes_index:
    path: /api/commandes
    controller: App\Controller\api\CommandeController::index
    methods: GET

api_commandes_show:
    path: /api/commandes/{id}
    controller: App\Controller\api\CommandeController::show
    methods: GET

api_commandes_create:
    path: /api/commandes
    controller: App\Controller\api\CommandeController::create
    methods: POST

api_commandes_update:
    path: /api/commandes/{id}
    controller: App\Controller\api\CommandeController::update
    methods: PUT

api_commandes_delete:
    path: /api/commandes/{id}
    controller: App\Controller\api\CommandeController::delete
    methods: DELETE
commercial:
    path: /commercial
    controller: App\Controller\IndexController::commercial
    requirements:
        role: ROLE_COMMERCIAL


